### ISSUE TITLE
Tenés que poner un espacio de más x dónde I'm learning Python... Porque si no queda descarado. 

### ISSUE THREAD

**Issue by AntuBoccalandro** [sami-heart/about-me#1]

**Comment by Samuussss** [comment]
yo hago lo q quiero sabes? 
*lo arregla*
xd

**Comment by AntuBoccalandro** [comment]
![IMG-20230612-WA0099.jpg](https://github.com/leanatr47/leanatr47/assets/110002821/7a80cda2-abe9-47f9-8c21-7f8822b56728)
